package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cmnddata extends Structure {
	/** Command value */
	public double val;
	/** Decimal point */
	public NativeLong dec;
	/** dummy */
	public NativeLong dummy;
	public cmnddata() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("val", "dec", "dummy");
	}
	public cmnddata(double val, NativeLong dec, NativeLong dummy) {
		super();
		this.val = val;
		this.dec = dec;
		this.dummy = dummy;
	}
	public cmnddata(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cmnddata implements Structure.ByReference {
		
	};
	public static class ByValue extends cmnddata implements Structure.ByValue {
		
	};
}
