package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class dcsfmoni extends Structure {
	/** Fixed Val */
	public NativeLong data_d;
	/** Present Val */
	public NativeLong data_p;
	public dcsfmoni() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("data_d", "data_p");
	}
	public dcsfmoni(NativeLong data_d, NativeLong data_p) {
		super();
		this.data_d = data_d;
		this.data_p = data_p;
	}
	public dcsfmoni(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends dcsfmoni implements Structure.ByReference {
		
	};
	public static class ByValue extends dcsfmoni implements Structure.ByValue {
		
	};
}
