package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class DNS_STATUS_INFO extends Structure {
	public byte Status;
	public byte MpuStatus;
	public byte MpuState;
	public byte MpuAlarmCode;
	public byte MpuVerInfo;
	public byte[] pad = new byte[3];
	public DNS_STATUS_INFO() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("Status", "MpuStatus", "MpuState", "MpuAlarmCode", "MpuVerInfo", "pad");
	}
	public DNS_STATUS_INFO(byte Status, byte MpuStatus, byte MpuState, byte MpuAlarmCode, byte MpuVerInfo, byte pad[]) {
		super();
		this.Status = Status;
		this.MpuStatus = MpuStatus;
		this.MpuState = MpuState;
		this.MpuAlarmCode = MpuAlarmCode;
		this.MpuVerInfo = MpuVerInfo;
		if ((pad.length != this.pad.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pad = pad;
	}
	public DNS_STATUS_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends DNS_STATUS_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends DNS_STATUS_INFO implements Structure.ByValue {
		
	};
}
