package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class EIPA_ALLOC_PRM extends Structure {
	public byte State;
	public byte Option;
	public byte[] pad = new byte[2];
	public EIP_TYPE_PRM DI;
	public EIP_TYPE_PRM DO;
	public EIPA_ALLOC_PRM() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("State", "Option", "pad", "DI", "DO");
	}
	public EIPA_ALLOC_PRM(byte State, byte Option, byte pad[], EIP_TYPE_PRM DI, EIP_TYPE_PRM DO) {
		super();
		this.State = State;
		this.Option = Option;
		if ((pad.length != this.pad.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pad = pad;
		this.DI = DI;
		this.DO = DO;
	}
	public EIPA_ALLOC_PRM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends EIPA_ALLOC_PRM implements Structure.ByReference {
		
	};
	public static class ByValue extends EIPA_ALLOC_PRM implements Structure.ByValue {
		
	};
}
