package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FACTO_CLIENT_PRM_FLG extends Structure {
	public byte HostName;
	public byte Port;
	public FACTO_CLIENT_PRM_FLG() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("HostName", "Port");
	}
	public FACTO_CLIENT_PRM_FLG(byte HostName, byte Port) {
		super();
		this.HostName = HostName;
		this.Port = Port;
	}
	public FACTO_CLIENT_PRM_FLG(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends FACTO_CLIENT_PRM_FLG implements Structure.ByReference {
		
	};
	public static class ByValue extends FACTO_CLIENT_PRM_FLG implements Structure.ByValue {
		
	};
}
