package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FTPPRM extends Structure {
	public byte[] FTPServerUserName = new byte[32];
	public byte[] FTPServerPassword = new byte[32];
	public byte[] FTPServerLoginDirectory = new byte[128];
	public FTPPRM() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("FTPServerUserName", "FTPServerPassword", "FTPServerLoginDirectory");
	}
	public FTPPRM(byte FTPServerUserName[], byte FTPServerPassword[], byte FTPServerLoginDirectory[]) {
		super();
		if ((FTPServerUserName.length != this.FTPServerUserName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.FTPServerUserName = FTPServerUserName;
		if ((FTPServerPassword.length != this.FTPServerPassword.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.FTPServerPassword = FTPServerPassword;
		if ((FTPServerLoginDirectory.length != this.FTPServerLoginDirectory.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.FTPServerLoginDirectory = FTPServerLoginDirectory;
	}
	public FTPPRM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends FTPPRM implements Structure.ByReference {
		
	};
	public static class ByValue extends FTPPRM implements Structure.ByValue {
		
	};
}
