package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class idblswork extends Structure {
	public short slct;
	public short skeyinf;
	public short[] reserve = new short[14];
	public idblswork() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("slct", "skeyinf", "reserve");
	}
	public idblswork(short slct, short skeyinf, short reserve[]) {
		super();
		this.slct = slct;
		this.skeyinf = skeyinf;
		if ((reserve.length != this.reserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.reserve = reserve;
	}
	public idblswork(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends idblswork implements Structure.ByReference {
		
	};
	public static class ByValue extends idblswork implements Structure.ByValue {
		
	};
}
