package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class idbsdtchan2 extends Structure {
	public short type;
	public byte chno;
	public byte axis;
	public short shift;
	public pmc_data[] io = new pmc_data[16];
	public idbsdtchan2() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("type", "chno", "axis", "shift", "io");
	}
	public idbsdtchan2(short type, byte chno, byte axis, short shift, pmc_data io[]) {
		super();
		this.type = type;
		this.chno = chno;
		this.axis = axis;
		this.shift = shift;
		if ((io.length != this.io.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.io = io;
	}
	public idbsdtchan2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends idbsdtchan2 implements Structure.ByReference {
		
	};
	public static class ByValue extends idbsdtchan2 implements Structure.ByValue {
		
	};
}
