package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class idbtwp_euler_fmt extends Structure {
	public double[] orign = new double[3];
	public double i;
	public double j;
	public double k;
	public NativeLong[] reserve = new NativeLong[24];
	public idbtwp_euler_fmt() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("orign", "i", "j", "k", "reserve");
	}
	public idbtwp_euler_fmt(double orign[], double i, double j, double k, NativeLong reserve[]) {
		super();
		if ((orign.length != this.orign.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.orign = orign;
		this.i = i;
		this.j = j;
		this.k = k;
		if ((reserve.length != this.reserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.reserve = reserve;
	}
	public idbtwp_euler_fmt(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends idbtwp_euler_fmt implements Structure.ByReference {
		
	};
	public static class ByValue extends idbtwp_euler_fmt implements Structure.ByValue {
		
	};
}
