package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class idbtlm_srchdt extends Structure {
	public idbtlm id_info;
	public short srch_cond;
	public short add_cond;
	public idbtlm_srchdt() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("id_info", "srch_cond", "add_cond");
	}
	public idbtlm_srchdt(idbtlm id_info, short srch_cond, short add_cond) {
		super();
		this.id_info = id_info;
		this.srch_cond = srch_cond;
		this.add_cond = add_cond;
	}
	public idbtlm_srchdt(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends idbtlm_srchdt implements Structure.ByReference {
		
	};
	public static class ByValue extends idbtlm_srchdt implements Structure.ByValue {
		
	};
}
