package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class idbunsolicmsg extends Structure {
	public short getno;
	public idbunsolicmsg.msg_struct[] msg = new idbunsolicmsg.msg_struct[3];
	public static class msg_struct extends Structure {
		public short rdsize;
		public Pointer data;
		public msg_struct() {
			super();
		}
		protected List<String> getFieldOrder() {
			return Arrays.asList("rdsize", "data");
		}
		public msg_struct(short rdsize, Pointer data) {
			super();
			this.rdsize = rdsize;
			this.data = data;
		}
		public msg_struct(Pointer peer) {
			super(peer);
		}
		public static class ByReference extends msg_struct implements Structure.ByReference {
			
		};
		public static class ByValue extends msg_struct implements Structure.ByValue {
			
		};
	};
	public idbunsolicmsg() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("getno", "msg");
	}
	public idbunsolicmsg(short getno, idbunsolicmsg.msg_struct msg[]) {
		super();
		this.getno = getno;
		if ((msg.length != this.msg.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.msg = msg;
	}
	public idbunsolicmsg(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends idbunsolicmsg implements Structure.ByReference {
		
	};
	public static class ByValue extends idbunsolicmsg implements Structure.ByValue {
		
	};
}
