package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IN_DNMPRMFLAG_BUS2 extends Structure {
	public byte Network;
	public byte BaudRate;
	public byte DiDataOnAbnormal;
	public byte OwnMacId;
	public byte CommonStatus;
	public byte CommonStatusSize;
	public byte CycleTimeSetting;
	public byte[] reserved1 = new byte[4];
	public byte Option;
	public byte[] reserved2 = new byte[4];
	public IN_DNMPRMFLAG_BUS2() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("Network", "BaudRate", "DiDataOnAbnormal", "OwnMacId", "CommonStatus", "CommonStatusSize", "CycleTimeSetting", "reserved1", "Option", "reserved2");
	}
	public IN_DNMPRMFLAG_BUS2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends IN_DNMPRMFLAG_BUS2 implements Structure.ByReference {
		
	};
	public static class ByValue extends IN_DNMPRMFLAG_BUS2 implements Structure.ByValue {
		
	};
}
