package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IN_EIPS_ALLOC extends Structure {
	public IN_EIPS_ALLOC_PRM_FLG flg;
	public EIPS_ALLOC_PRM prm;
	public IN_EIPS_ALLOC() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("flg", "prm");
	}
	public IN_EIPS_ALLOC(IN_EIPS_ALLOC_PRM_FLG flg, EIPS_ALLOC_PRM prm) {
		super();
		this.flg = flg;
		this.prm = prm;
	}
	public IN_EIPS_ALLOC(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends IN_EIPS_ALLOC implements Structure.ByReference {
		
	};
	public static class ByValue extends IN_EIPS_ALLOC implements Structure.ByValue {
		
	};
}
