package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IN_EIPS_CONN_PRM_FLG extends Structure {
	public byte AssemblyInstance;
	public byte Type;
	public byte Addr;
	public byte Size;
	public byte RPI;
	public byte TransportType;
	public byte HeaderFormat;
	public byte Priority;
	public byte reserve;
	public byte[] pad = new byte[3];
	public IN_EIPS_CONN_PRM_FLG() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("AssemblyInstance", "Type", "Addr", "Size", "RPI", "TransportType", "HeaderFormat", "Priority", "reserve", "pad");
	}
	public IN_EIPS_CONN_PRM_FLG(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends IN_EIPS_CONN_PRM_FLG implements Structure.ByReference {
		
	};
	public static class ByValue extends IN_EIPS_CONN_PRM_FLG implements Structure.ByValue {
		
	};
}
