package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class iodbtd2 extends Structure {
	/** tool group number */
	public short datano;
	/** dummy */
	public short dummy;
	/** tool using number */
	public NativeLong type;
	/** tool number */
	public NativeLong tool_num;
	/** H code */
	public NativeLong h_code;
	/** D code */
	public NativeLong d_code;
	/** tool information */
	public NativeLong tool_inf;
	public iodbtd2() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("datano", "dummy", "type", "tool_num", "h_code", "d_code", "tool_inf");
	}
	public iodbtd2(short datano, short dummy, NativeLong type, NativeLong tool_num, NativeLong h_code, NativeLong d_code, NativeLong tool_inf) {
		super();
		this.datano = datano;
		this.dummy = dummy;
		this.type = type;
		this.tool_num = tool_num;
		this.h_code = h_code;
		this.d_code = d_code;
		this.tool_inf = tool_inf;
	}
	public iodbtd2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends iodbtd2 implements Structure.ByReference {
		
	};
	public static class ByValue extends iodbtd2 implements Structure.ByValue {
		
	};
}
