package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class iodbtlgsext extends Structure {
	/** tool data1 */
	public NativeLong data1;
	/** tool data2 */
	public NativeLong data2;
	/** tool data3 */
	public NativeLong data3;
	/** tool data4 */
	public NativeLong data4;
	/** tool kind */
	public byte tooltype;
	/** attach */
	public byte install;
	/** holder */
	public byte holder;
	/** tool name */
	public byte[] toolname = new byte[9];
	public iodbtlgsext() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("data1", "data2", "data3", "data4", "tooltype", "install", "holder", "toolname");
	}
	public iodbtlgsext(NativeLong data1, NativeLong data2, NativeLong data3, NativeLong data4, byte tooltype, byte install, byte holder, byte toolname[]) {
		super();
		this.data1 = data1;
		this.data2 = data2;
		this.data3 = data3;
		this.data4 = data4;
		this.tooltype = tooltype;
		this.install = install;
		this.holder = holder;
		if ((toolname.length != this.toolname.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.toolname = toolname;
	}
	public iodbtlgsext(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends iodbtlgsext implements Structure.ByReference {
		
	};
	public static class ByValue extends iodbtlgsext implements Structure.ByValue {
		
	};
}
