package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class iodbpi extends Structure {
	/** start pitch number */
	public short datano_s;
	/** dummy */
	public short dummy;
	/** end pitch number */
	public short datano_e;
	/** offset value */
	public byte[] data = new byte[5];
	public iodbpi() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("datano_s", "dummy", "datano_e", "data");
	}
	public iodbpi(short datano_s, short dummy, short datano_e, byte data[]) {
		super();
		this.datano_s = datano_s;
		this.dummy = dummy;
		this.datano_e = datano_e;
		if ((data.length != this.data.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.data = data;
	}
	public iodbpi(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends iodbpi implements Structure.ByReference {
		
	};
	public static class ByValue extends iodbpi implements Structure.ByValue {
		
	};
}
