package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class iodbrbsummary extends Structure {
	public byte signal_type;
	public byte reserve;
	public short no;
	public iodbrbsummary() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("signal_type", "reserve", "no");
	}
	public iodbrbsummary(byte signal_type, byte reserve, short no) {
		super();
		this.signal_type = signal_type;
		this.reserve = reserve;
		this.no = no;
	}
	public iodbrbsummary(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends iodbrbsummary implements Structure.ByReference {
		
	};
	public static class ByValue extends iodbrbsummary implements Structure.ByValue {
		
	};
}
