package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class iodbrct_grpptn extends Structure {
	/** grp number */
	public short grp_num;
	/** dummy */
	public short ptn_num;
	public iodbrct_grpptn() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("grp_num", "ptn_num");
	}
	public iodbrct_grpptn(short grp_num, short ptn_num) {
		super();
		this.grp_num = grp_num;
		this.ptn_num = ptn_num;
	}
	public iodbrct_grpptn(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends iodbrct_grpptn implements Structure.ByReference {
		
	};
	public static class ByValue extends iodbrct_grpptn implements Structure.ByValue {
		
	};
}
