package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class iodblcmdt extends Structure {
	public short slct;
	public NativeLong feed;
	public short power;
	public short freq;
	public short duty;
	public short g_kind;
	public short g_ready_t;
	public short g_press;
	public short error;
	public NativeLong dsplc;
	public NativeLong error2;
	public byte gap_axis;
	public byte feed_dec;
	public byte dsplc_dec;
	public byte error2_dec;
	public short[] reserve = new short[3];
	public iodblcmdt() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("slct", "feed", "power", "freq", "duty", "g_kind", "g_ready_t", "g_press", "error", "dsplc", "error2", "gap_axis", "feed_dec", "dsplc_dec", "error2_dec", "reserve");
	}
	public iodblcmdt(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends iodblcmdt implements Structure.ByReference {
		
	};
	public static class ByValue extends iodblcmdt implements Structure.ByValue {
		
	};
}
