package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class iodbtl_retype extends Structure {
	public byte type;
	public byte data_type;
	public byte renew;
	public byte reserve;
	public iodbtl_retype() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("type", "data_type", "renew", "reserve");
	}
	public iodbtl_retype(byte type, byte data_type, byte renew, byte reserve) {
		super();
		this.type = type;
		this.data_type = data_type;
		this.renew = renew;
		this.reserve = reserve;
	}
	public iodbtl_retype(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends iodbtl_retype implements Structure.ByReference {
		
	};
	public static class ByValue extends iodbtl_retype implements Structure.ByValue {
		
	};
}
