package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class iodbsuofs extends Structure {
	/** vector element */
	public NativeLong vect_val;
	/** fraction digit */
	public NativeLong frc_dgt;
	public iodbsuofs() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("vect_val", "frc_dgt");
	}
	public iodbsuofs(NativeLong vect_val, NativeLong frc_dgt) {
		super();
		this.vect_val = vect_val;
		this.frc_dgt = frc_dgt;
	}
	public iodbsuofs(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends iodbsuofs implements Structure.ByReference {
		
	};
	public static class ByValue extends iodbsuofs implements Structure.ByValue {
		
	};
}
