package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class iodbsfsgsighis extends Structure {
	public short sno_sig;
	public short len_sig;
	public short sno_sig_his;
	public short len_sig_his;
	public short extract;
	public iodbsfsgsighis() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("sno_sig", "len_sig", "sno_sig_his", "len_sig_his", "extract");
	}
	public iodbsfsgsighis(short sno_sig, short len_sig, short sno_sig_his, short len_sig_his, short extract) {
		super();
		this.sno_sig = sno_sig;
		this.len_sig = len_sig;
		this.sno_sig_his = sno_sig_his;
		this.len_sig_his = len_sig_his;
		this.extract = extract;
	}
	public iodbsfsgsighis(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends iodbsfsgsighis implements Structure.ByReference {
		
	};
	public static class ByValue extends iodbsfsgsighis implements Structure.ByValue {
		
	};
}
