package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class iodbcprm extends Structure {
	public byte[] NcApli = new byte[65];
	public byte Dummy1;
	public byte[] HostApli = new byte[65];
	public byte Dummy2;
	public NativeLong StatPstv;
	public NativeLong StatNgtv;
	public NativeLong Statmask;
	public NativeLong AlarmStat;
	public NativeLong PsclHaddr;
	public NativeLong PsclLaddr;
	public short SvcMode1;
	public short SvcMode2;
	public NativeLong FileTout;
	public NativeLong RemTout;
	public iodbcprm() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("NcApli", "Dummy1", "HostApli", "Dummy2", "StatPstv", "StatNgtv", "Statmask", "AlarmStat", "PsclHaddr", "PsclLaddr", "SvcMode1", "SvcMode2", "FileTout", "RemTout");
	}
	public iodbcprm(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends iodbcprm implements Structure.ByReference {
		
	};
	public static class ByValue extends iodbcprm implements Structure.ByValue {
		
	};
}
