package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class iodbrtmio extends Structure {
	public short adr_type;
	public short dummy;
	public NativeLong no;
	public byte bit;
	public iodbrtmio() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("adr_type", "dummy", "no", "bit");
	}
	public iodbrtmio(short adr_type, short dummy, NativeLong no, byte bit) {
		super();
		this.adr_type = adr_type;
		this.dummy = dummy;
		this.no = no;
		this.bit = bit;
	}
	public iodbrtmio(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends iodbrtmio implements Structure.ByReference {
		
	};
	public static class ByValue extends iodbrtmio implements Structure.ByValue {
		
	};
}
