package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class iodbint extends Structure {
	/** start offset No. */
	public short datano_s;
	/** kind of position */
	public short type;
	/** end offset No. */
	public short datano_e;
	/** position value of area for not attach */
	public NativeLong[] data = new NativeLong[24];
	public iodbint() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("datano_s", "type", "datano_e", "data");
	}
	public iodbint(short datano_s, short type, short datano_e, NativeLong data[]) {
		super();
		this.datano_s = datano_s;
		this.type = type;
		this.datano_e = datano_e;
		if ((data.length != this.data.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.data = data;
	}
	public iodbint(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends iodbint implements Structure.ByReference {
		
	};
	public static class ByValue extends iodbint implements Structure.ByValue {
		
	};
}
