package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class iodbtool_outhis extends Structure {
	public short tool_no;
	public short cause;
	public iodbtool_date date;
	public iodbtlmng_f2 tool_f2;
	public iodbtool_outhis() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("tool_no", "cause", "date", "tool_f2");
	}
	public iodbtool_outhis(short tool_no, short cause, iodbtool_date date, iodbtlmng_f2 tool_f2) {
		super();
		this.tool_no = tool_no;
		this.cause = cause;
		this.date = date;
		this.tool_f2 = tool_f2;
	}
	public iodbtool_outhis(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends iodbtool_outhis implements Structure.ByReference {
		
	};
	public static class ByValue extends iodbtool_outhis implements Structure.ByValue {
		
	};
}
