package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class MAINTAIN_PRM extends Structure {
	public PING_PRM opposite;
	public MAINTAIN_PRM() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("opposite");
	}
	public MAINTAIN_PRM(PING_PRM opposite) {
		super();
		this.opposite = opposite;
	}
	public MAINTAIN_PRM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends MAINTAIN_PRM implements Structure.ByReference {
		
	};
	public static class ByValue extends MAINTAIN_PRM implements Structure.ByValue {
		
	};
}
