package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class MBSVR_AREA_PRM extends Structure {
	public NativeLong DatSize;
	public NativeLong DatModAddr;
	public PMC_ADDR DatPmcAddr;
	public MBSVR_AREA_PRM() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("DatSize", "DatModAddr", "DatPmcAddr");
	}
	public MBSVR_AREA_PRM(NativeLong DatSize, NativeLong DatModAddr, PMC_ADDR DatPmcAddr) {
		super();
		this.DatSize = DatSize;
		this.DatModAddr = DatModAddr;
		this.DatPmcAddr = DatPmcAddr;
	}
	public MBSVR_AREA_PRM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends MBSVR_AREA_PRM implements Structure.ByReference {
		
	};
	public static class ByValue extends MBSVR_AREA_PRM implements Structure.ByValue {
		
	};
}
