package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbbinfo extends Structure {
	public short iochno;
	public short grpno;
	public short axis;
	public byte name;
	public byte suff;
	public short[] reserve = new short[3];
	public odbbinfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("iochno", "grpno", "axis", "name", "suff", "reserve");
	}
	public odbbinfo(short iochno, short grpno, short axis, byte name, byte suff, short reserve[]) {
		super();
		this.iochno = iochno;
		this.grpno = grpno;
		this.axis = axis;
		this.name = name;
		this.suff = suff;
		if ((reserve.length != this.reserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.reserve = reserve;
	}
	public odbbinfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbbinfo implements Structure.ByReference {
		
	};
	public static class ByValue extends odbbinfo implements Structure.ByValue {
		
	};
}
