package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbbrs extends Structure {
	public NativeLong[] dest = new NativeLong[32];
	public NativeLong[] dist = new NativeLong[32];
	public odbbrs() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("dest", "dist");
	}
	public odbbrs(NativeLong dest[], NativeLong dist[]) {
		super();
		if ((dest.length != this.dest.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.dest = dest;
		if ((dist.length != this.dist.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.dist = dist;
	}
	public odbbrs(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbbrs implements Structure.ByReference {
		
	};
	public static class ByValue extends odbbrs implements Structure.ByValue {
		
	};
}
