package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbdiagnum extends Structure {
	public short diag_min;
	public short diag_max;
	public short total_no;
	public odbdiagnum() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("diag_min", "diag_max", "total_no");
	}
	public odbdiagnum(short diag_min, short diag_max, short total_no) {
		super();
		this.diag_min = diag_min;
		this.diag_max = diag_max;
		this.total_no = total_no;
	}
	public odbdiagnum(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbdiagnum implements Structure.ByReference {
		
	};
	public static class ByValue extends odbdiagnum implements Structure.ByValue {
		
	};
}
