package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbembedfinf extends Structure {
	/** used capacity */
	public NativeLong used_page;
	/** all capacity */
	public NativeLong all_page;
	public odbembedfinf() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("used_page", "all_page");
	}
	public odbembedfinf(NativeLong used_page, NativeLong all_page) {
		super();
		this.used_page = used_page;
		this.all_page = all_page;
	}
	public odbembedfinf(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbembedfinf implements Structure.ByReference {
		
	};
	public static class ByValue extends odbembedfinf implements Structure.ByValue {
		
	};
}
