package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbfinfo extends Structure {
	/** Slot Name */
	public byte[] slotname = new byte[12];
	/** Number of F-ROM SYSTEM data */
	public NativeLong fromnum;
	public fwlib32.odbparaif.info_struct[] info = new fwlib32.odbparaif.info_struct[32];
	public static class info_struct extends Structure {
		/** F-ROM SYSTEM data Name */
		public byte[] sysname = new byte[12];
		/** F-ROM Size */
		public NativeLong fromsize;
		public info_struct() {
			super();
		}
		protected List<? > getFieldOrder() {
			return Arrays.asList("sysname", "fromsize");
		}
		public info_struct(byte sysname[], NativeLong fromsize) {
			super();
			if ((sysname.length != this.sysname.length)) 
				throw new IllegalArgumentException("Wrong array size !");
			this.sysname = sysname;
			this.fromsize = fromsize;
		}
		public info_struct(Pointer peer) {
			super(peer);
		}
		public static class ByReference extends info_struct implements Structure.ByReference {
			
		};
		public static class ByValue extends info_struct implements Structure.ByValue {
			
		};
	};
	public odbfinfo() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("slotname", "fromnum", "info");
	}
	public odbfinfo(byte slotname[], NativeLong fromnum, fwlib32.odbparaif.info_struct info[]) {
		super();
		if ((slotname.length != this.slotname.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.slotname = slotname;
		this.fromnum = fromnum;
		if ((info.length != this.info.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.info = info;
	}
	public odbfinfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbfinfo implements Structure.ByReference {
		
	};
	public static class ByValue extends odbfinfo implements Structure.ByValue {
		
	};
}
