package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbgrpaxis extends Structure {
	/** Path number */
	public short path_num;
	/** Drawing axis number */
	public short draw_num;
	public odbgrpaxis() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("path_num", "draw_num");
	}
	public odbgrpaxis(short path_num, short draw_num) {
		super();
		this.path_num = path_num;
		this.draw_num = draw_num;
	}
	public odbgrpaxis(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbgrpaxis implements Structure.ByReference {
		
	};
	public static class ByValue extends odbgrpaxis implements Structure.ByValue {
		
	};
}
