package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbgcd extends Structure {
	public short group;
	public short flag;
	public byte[] code = new byte[8];
	public odbgcd() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("group", "flag", "code");
	}
	public odbgcd(short group, short flag, byte code[]) {
		super();
		this.group = group;
		this.flag = flag;
		if ((code.length != this.code.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.code = code;
	}
	public odbgcd(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbgcd implements Structure.ByReference {
		
	};
	public static class ByValue extends odbgcd implements Structure.ByValue {
		
	};
}
