package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbjogcmd extends Structure {
	/** G code */
	public iodbjogcmdcode gcode;
	/** M code */
	public iodbjogcmdcode mcode;
	/** S code */
	public iodbjogcmdcode scode;
	/** T code */
	public iodbjogcmdcode tcode;
	/** B code */
	public iodbjogcmdcode bcode;
	/** address P */
	public iodbjogcmdcode padr;
	/** extension S code */
	public iodbjogcmdscode[] extscode = new iodbjogcmdscode[4];
	/** axis */
	public iodbjogcmdaxis[] axis = new iodbjogcmdaxis[32];
	/** axis count */
	public NativeLong axis_cnt;
	public odbjogcmd() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("gcode", "mcode", "scode", "tcode", "bcode", "padr", "extscode", "axis", "axis_cnt");
	}
	public odbjogcmd(iodbjogcmdcode gcode, iodbjogcmdcode mcode, iodbjogcmdcode scode, iodbjogcmdcode tcode, iodbjogcmdcode bcode, iodbjogcmdcode padr, iodbjogcmdscode extscode[], iodbjogcmdaxis axis[], NativeLong axis_cnt) {
		super();
		this.gcode = gcode;
		this.mcode = mcode;
		this.scode = scode;
		this.tcode = tcode;
		this.bcode = bcode;
		this.padr = padr;
		if ((extscode.length != this.extscode.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.extscode = extscode;
		if ((axis.length != this.axis.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.axis = axis;
		this.axis_cnt = axis_cnt;
	}
	public odbjogcmd(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbjogcmd implements Structure.ByReference {
		
	};
	public static class ByValue extends odbjogcmd implements Structure.ByValue {
		
	};
}
