package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odblofs extends Structure {
	public short mode;
	public NativeLong[] ofsvct = new NativeLong[32];
	public odblofs() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("mode", "ofsvct");
	}
	public odblofs(short mode, NativeLong ofsvct[]) {
		super();
		this.mode = mode;
		if ((ofsvct.length != this.ofsvct.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ofsvct = ofsvct;
	}
	public odblofs(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odblofs implements Structure.ByReference {
		
	};
	public static class ByValue extends odblofs implements Structure.ByValue {
		
	};
}
