package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbmdgmsg extends Structure {
	public NativeLong alm_no;
	public short msgidx;
	public short reserved;
	public byte[] type = new byte[4];
	public byte[] part = new byte[4];
	public byte[] level = new byte[4];
	public byte[] add_inf = new byte[4];
	public byte[] mark = new byte[20];
	public byte[] message = new byte[100];
	public byte[] cause = new byte[300];
	public odbmdgmsg() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("alm_no", "msgidx", "reserved", "type", "part", "level", "add_inf", "mark", "message", "cause");
	}
	public odbmdgmsg(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbmdgmsg implements Structure.ByReference {
		
	};
	public static class ByValue extends odbmdgmsg implements Structure.ByValue {
		
	};
}
