package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbmsrncdat extends Structure {
	public short sv_num;
	public short sp_num;
	public odbaxdt[] mcn = new odbaxdt[32];
	public odbaxdt[] abs = new odbaxdt[32];
	public odbaxdt[] spdl = new odbaxdt[8];
	public odbaxdt actf;
	public byte[] ex_prg_name = new byte[248];
	public NativeLong ex_blk;
	public short aut;
	public short tmmode;
	public odbcmd[] m_mdl = new odbcmd[5];
	public odbcmd s_mdl;
	public odbcmd t_mdl;
	public odbcmd b_mdl;
	public odbmsrncdat() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("sv_num", "sp_num", "mcn", "abs", "spdl", "actf", "ex_prg_name", "ex_blk", "aut", "tmmode", "m_mdl", "s_mdl", "t_mdl", "b_mdl");
	}
	public odbmsrncdat(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbmsrncdat implements Structure.ByReference {
		
	};
	public static class ByValue extends odbmsrncdat implements Structure.ByValue {
		
	};
}
