package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbnme extends Structure {
	/** object type */
	public short ob_type;
	/** object number */
	public short obj_no;
	/** name number */
	public short nme_no;
	/** suffix */
	public short suffix;
	/** optional name */
	public byte[] name = new byte[12];
	public odbnme() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ob_type", "obj_no", "nme_no", "suffix", "name");
	}
	public odbnme(short ob_type, short obj_no, short nme_no, short suffix, byte name[]) {
		super();
		this.ob_type = ob_type;
		this.obj_no = obj_no;
		this.nme_no = nme_no;
		this.suffix = suffix;
		if ((name.length != this.name.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.name = name;
	}
	public odbnme(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbnme implements Structure.ByReference {
		
	};
	public static class ByValue extends odbnme implements Structure.ByValue {
		
	};
}
