package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbpthis_ax extends Structure {
	public double l_value;
	public double l_value_e;
	public double pos_value;
	public double pos_value_e;
	public double l_value_sub;
	public double l_value_e_sub;
	public double l_value_cycle;
	public double l_value_e_cycle;
	public NativeLong repeat_sub;
	public NativeLong repeat_e_sub;
	public NativeLong info1;
	public short number;
	public short number_sub;
	public short number_cycle;
	public short table_kind;
	public byte[] name = new byte[4];
	public byte cs_spdl_idx_pt;
	public byte cs_spdl_idx_rel;
	public byte master_indx_no_pt;
	public byte master_indx_no_rel;
	public byte pos_frac;
	public byte l_frac;
	public byte l_frac_cycle;
	public byte reserve1;
	public odbpthis_ax() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("l_value", "l_value_e", "pos_value", "pos_value_e", "l_value_sub", "l_value_e_sub", "l_value_cycle", "l_value_e_cycle", "repeat_sub", "repeat_e_sub", "info1", "number", "number_sub", "number_cycle", "table_kind", "name", "cs_spdl_idx_pt", "cs_spdl_idx_rel", "master_indx_no_pt", "master_indx_no_rel", "pos_frac", "l_frac", "l_frac_cycle", "reserve1");
	}
	public odbpthis_ax(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbpthis_ax implements Structure.ByReference {
		
	};
	public static class ByValue extends odbpthis_ax implements Structure.ByValue {
		
	};
}
