package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbpthis_pt extends Structure {
	public double time;
	public short dist_err;
	public short ov_time;
	public NativeLong info1;
	public short alarm_no;
	public byte alarm_type;
	public byte alarm_axis;
	public byte path_axis_num;
	public byte path_spdl_num;
	public byte time_frac;
	public byte reserve1;
	public odbpthis_pt() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("time", "dist_err", "ov_time", "info1", "alarm_no", "alarm_type", "alarm_axis", "path_axis_num", "path_spdl_num", "time_frac", "reserve1");
	}
	public odbpthis_pt(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbpthis_pt implements Structure.ByReference {
		
	};
	public static class ByValue extends odbpthis_pt implements Structure.ByValue {
		
	};
}
