package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbpdfnfil extends Structure {
	/** directory */
	public short dir_num;
	/** file */
	public short file_num;
	public odbpdfnfil() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("dir_num", "file_num");
	}
	public odbpdfnfil(short dir_num, short file_num) {
		super();
		this.dir_num = dir_num;
		this.file_num = file_num;
	}
	public odbpdfnfil(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbpdfnfil implements Structure.ByReference {
		
	};
	public static class ByValue extends odbpdfnfil implements Structure.ByValue {
		
	};
}
