package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbpmvalflg extends Structure {
	public short exe_type;
	public short aux_type;
	public short tlk_type;
	public odbpmvalflg() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("exe_type", "aux_type", "tlk_type");
	}
	public odbpmvalflg(short exe_type, short aux_type, short tlk_type) {
		super();
		this.exe_type = exe_type;
		this.aux_type = aux_type;
		this.tlk_type = tlk_type;
	}
	public odbpmvalflg(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbpmvalflg implements Structure.ByReference {
		
	};
	public static class ByValue extends odbpmvalflg implements Structure.ByValue {
		
	};
}
