package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbprfinfo extends Structure {
	public short series;
	public short vers1;
	public short vers2;
	public short profi;
	public odbprfinfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("series", "vers1", "vers2", "profi");
	}
	public odbprfinfo(short series, short vers1, short vers2, short profi) {
		super();
		this.series = series;
		this.vers1 = vers1;
		this.vers2 = vers2;
		this.profi = profi;
	}
	public odbprfinfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbprfinfo implements Structure.ByReference {
		
	};
	public static class ByValue extends odbprfinfo implements Structure.ByValue {
		
	};
}
