package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbpmcaxisinfo extends Structure {
	/** active / nonactive */
	public byte datastatus;
	/** axis status */
	public byte axisstatus;
	/** command signal */
	public byte commandsignal;
	/** status signal */
	public byte statussignal;
	/** boundary alignment */
	public byte dummy;
	/** instruction number */
	public byte instruction;
	/** speed signal */
	public short speedsignal;
	/** data signal */
	public NativeLong axisctrldata;
	/** subinstruction number */
	public short subinstnum;
	/** data length of subinstruction */
	public short subinstlength;
	/** subinstruction data 1 */
	public NativeLong subinstdata1;
	/** subinstruction data 2 */
	public NativeLong subinstdata2;
	/** subinstruction data 3 */
	public NativeLong subinstdata3;
	/** subinstruction data 4 */
	public NativeLong subinstdata4;
	/** subinstruction data 5 */
	public NativeLong subinstdata5;
	/** subinstruction data 6 */
	public NativeLong subinstdata6;
	/** subinstruction data 7 */
	public NativeLong subinstdata7;
	public odbpmcaxisinfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("datastatus", "axisstatus", "commandsignal", "statussignal", "dummy", "instruction", "speedsignal", "axisctrldata", "subinstnum", "subinstlength", "subinstdata1", "subinstdata2", "subinstdata3", "subinstdata4", "subinstdata5", "subinstdata6", "subinstdata7");
	}
	public odbpmcaxisinfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbpmcaxisinfo implements Structure.ByReference {
		
	};
	public static class ByValue extends odbpmcaxisinfo implements Structure.ByValue {
		
	};
}
