package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbsysc extends Structure {
	public byte[] slot_no_p = new byte[16];
	public byte[] slot_no_l = new byte[16];
	public short[] mod_id = new short[16];
	public short[] soft_id = new short[16];
	public byte[] s_series = new byte[((16) * (5))];
	public byte[] s_version = new byte[((16) * (5))];
	public byte[] dummy = new byte[16];
	public short m_rom;
	public short s_rom;
	public byte[] svo_soft = new byte[8];
	public byte[] pmc_soft = new byte[6];
	public byte[] lad_soft = new byte[6];
	public byte[] mcr_soft = new byte[8];
	public byte[] spl1_soft = new byte[6];
	public byte[] spl2_soft = new byte[6];
	public short frmmin;
	public short drmmin;
	public short srmmin;
	public short pmcmin;
	public short crtmin;
	public short sv1min;
	public short sv3min;
	public short sicmin;
	public short posmin;
	public short drmmrc;
	public short drmarc;
	public short pmcmrc;
	public short dmaarc;
	public short iopt;
	public short hdiio;
	public short frmsub;
	public short drmsub;
	public short srmsub;
	public short sv5sub;
	public short sv7sub;
	public short sicsub;
	public short possub;
	public short hamsub;
	public short gm2gr1;
	public short crtgr2;
	public short gm1gr2;
	public short gm2gr2;
	public short cmmrb;
	public short sv5axs;
	public short sv7axs;
	public short sicaxs;
	public short posaxs;
	public short hanaxs;
	public short romr64;
	public short srmr64;
	public short dr1r64;
	public short dr2r64;
	public short iopio2;
	public short hdiio2;
	public short cmmrb2;
	public short romfap;
	public short srmfap;
	public short drmfap;
	public odbsysc() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("slot_no_p", "slot_no_l", "mod_id", "soft_id", "s_series", "s_version", "dummy", "m_rom", "s_rom", "svo_soft", "pmc_soft", "lad_soft", "mcr_soft", "spl1_soft", "spl2_soft", "frmmin", "drmmin", "srmmin", "pmcmin", "crtmin", "sv1min", "sv3min", "sicmin", "posmin", "drmmrc", "drmarc", "pmcmrc", "dmaarc", "iopt", "hdiio", "frmsub", "drmsub", "srmsub", "sv5sub", "sv7sub", "sicsub", "possub", "hamsub", "gm2gr1", "crtgr2", "gm1gr2", "gm2gr2", "cmmrb", "sv5axs", "sv7axs", "sicaxs", "posaxs", "hanaxs", "romr64", "srmr64", "dr1r64", "dr2r64", "iopio2", "hdiio2", "cmmrb2", "romfap", "srmfap", "drmfap");
	}
	public odbsysc(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbsysc implements Structure.ByReference {
		
	};
	public static class ByValue extends odbsysc implements Structure.ByValue {
		
	};
}
