package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbsv2_grp2 extends Structure {
	public odbmdgdt mt_cur;
	public short trq_cmd;
	public short efc_cur;
	public short dlvl;
	public short heat;
	public short opt;
	public short opt2;
	public odbsv2_grp2() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("mt_cur", "trq_cmd", "efc_cur", "dlvl", "heat", "opt", "opt2");
	}
	public odbsv2_grp2(odbmdgdt mt_cur, short trq_cmd, short efc_cur, short dlvl, short heat, short opt, short opt2) {
		super();
		this.mt_cur = mt_cur;
		this.trq_cmd = trq_cmd;
		this.efc_cur = efc_cur;
		this.dlvl = dlvl;
		this.heat = heat;
		this.opt = opt;
		this.opt2 = opt2;
	}
	public odbsv2_grp2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbsv2_grp2 implements Structure.ByReference {
		
	};
	public static class ByValue extends odbsv2_grp2 implements Structure.ByValue {
		
	};
}
