package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbsfsgalmtime extends Structure {
	public short year;
	public short month;
	public short date;
	public short hour;
	public short minute;
	public short second;
	public odbsfsgalmtime() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("year", "month", "date", "hour", "minute", "second");
	}
	public odbsfsgalmtime(short year, short month, short date, short hour, short minute, short second) {
		super();
		this.year = year;
		this.month = month;
		this.date = date;
		this.hour = hour;
		this.minute = minute;
		this.second = second;
	}
	public odbsfsgalmtime(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbsfsgalmtime implements Structure.ByReference {
		
	};
	public static class ByValue extends odbsfsgalmtime implements Structure.ByValue {
		
	};
}
