package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbsp2_grp8 extends Structure {
	public short isncr_intp;
	public short isncr_com;
	public short isncr_wrn;
	public short esncr_intp;
	public short esncr_com;
	public short esncr_wrn;
	public short sp_dat1;
	public short sp_dat2;
	public short sp_dat3;
	public short sp_dat4;
	public odbsp2_grp8() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("isncr_intp", "isncr_com", "isncr_wrn", "esncr_intp", "esncr_com", "esncr_wrn", "sp_dat1", "sp_dat2", "sp_dat3", "sp_dat4");
	}
	public odbsp2_grp8(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbsp2_grp8 implements Structure.ByReference {
		
	};
	public static class ByValue extends odbsp2_grp8 implements Structure.ByValue {
		
	};
}
