package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbsp2_grp6 extends Structure {
	public short sp_up_err1;
	public short sp_up_err2;
	public short sp_lw_err1;
	public short sp_lw_err2;
	public short sp_up_jt1;
	public short sp_up_jt2;
	public short sp_lw_jt1;
	public short sp_lw_jt2;
	public odbsp2_grp6() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("sp_up_err1", "sp_up_err2", "sp_lw_err1", "sp_lw_err2", "sp_up_jt1", "sp_up_jt2", "sp_lw_jt1", "sp_lw_jt2");
	}
	public odbsp2_grp6(short sp_up_err1, short sp_up_err2, short sp_lw_err1, short sp_lw_err2, short sp_up_jt1, short sp_up_jt2, short sp_lw_jt1, short sp_lw_jt2) {
		super();
		this.sp_up_err1 = sp_up_err1;
		this.sp_up_err2 = sp_up_err2;
		this.sp_lw_err1 = sp_lw_err1;
		this.sp_lw_err2 = sp_lw_err2;
		this.sp_up_jt1 = sp_up_jt1;
		this.sp_up_jt2 = sp_up_jt2;
		this.sp_lw_jt1 = sp_lw_jt1;
		this.sp_lw_jt2 = sp_lw_jt2;
	}
	public odbsp2_grp6(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbsp2_grp6 implements Structure.ByReference {
		
	};
	public static class ByValue extends odbsp2_grp6 implements Structure.ByValue {
		
	};
}
