package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbsp2_grp7 extends Structure {
	public odbmdgdt iab_amplt;
	public odbmdgdt eab_amplt;
	public short iab_ofs_a;
	public short iab_ofs_b;
	public short iab_noise;
	public short eab_ofs_a;
	public short eab_ofs_b;
	public short eab_noise;
	public short iab_max_flt;
	public short eab_max_flt;
	public odbsp2_grp7() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("iab_amplt", "eab_amplt", "iab_ofs_a", "iab_ofs_b", "iab_noise", "eab_ofs_a", "eab_ofs_b", "eab_noise", "iab_max_flt", "eab_max_flt");
	}
	public odbsp2_grp7(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbsp2_grp7 implements Structure.ByReference {
		
	};
	public static class ByValue extends odbsp2_grp7 implements Structure.ByValue {
		
	};
}
