package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbspeed extends Structure {
	/** actual feed rate */
	public speedelm actf;
	/**
	 * SPEEDELM    acts;   /* actual spindle speed * /<br>
	 * type = 1,-1 : actual spindle speed
	 */
	public speedelm acts;
	public odbspeed() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("actf", "acts");
	}
	public odbspeed(speedelm actf, speedelm acts) {
		super();
		this.actf = actf;
		this.acts = acts;
	}
	public odbspeed(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbspeed implements Structure.ByReference {
		
	};
	public static class ByValue extends odbspeed implements Structure.ByValue {
		
	};
}
