package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbsv2_grp3 extends Structure {
	public odbmdgdt ps_vumb;
	public odbmdgdt ps_vthd;
	public odbmdgdt freq;
	public short ps_vrms;
	public short ps_cur;
	public short dvolt;
	public byte ps_statf;
	public byte reserved;
	public odbsv2_grp3() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("ps_vumb", "ps_vthd", "freq", "ps_vrms", "ps_cur", "dvolt", "ps_statf", "reserved");
	}
	public odbsv2_grp3(odbmdgdt ps_vumb, odbmdgdt ps_vthd, odbmdgdt freq, short ps_vrms, short ps_cur, short dvolt, byte ps_statf, byte reserved) {
		super();
		this.ps_vumb = ps_vumb;
		this.ps_vthd = ps_vthd;
		this.freq = freq;
		this.ps_vrms = ps_vrms;
		this.ps_cur = ps_cur;
		this.dvolt = dvolt;
		this.ps_statf = ps_statf;
		this.reserved = reserved;
	}
	public odbsv2_grp3(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbsv2_grp3 implements Structure.ByReference {
		
	};
	public static class ByValue extends odbsv2_grp3 implements Structure.ByValue {
		
	};
}
