package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbsfsgalm extends Structure {
	public short alm_type;
	public short alm_no;
	public odbsfsgalm() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("alm_type", "alm_no");
	}
	public odbsfsgalm(short alm_type, short alm_no) {
		super();
		this.alm_type = alm_type;
		this.alm_no = alm_no;
	}
	public odbsfsgalm(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbsfsgalm implements Structure.ByReference {
		
	};
	public static class ByValue extends odbsfsgalm implements Structure.ByValue {
		
	};
}
