package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbtlinf2 extends Structure {
	public short ofs_type;
	public short use_no;
	public short ofs_enable;
	public odbtlinf2() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ofs_type", "use_no", "ofs_enable");
	}
	public odbtlinf2(short ofs_type, short use_no, short ofs_enable) {
		super();
		this.ofs_type = ofs_type;
		this.use_no = use_no;
		this.ofs_enable = ofs_enable;
	}
	public odbtlinf2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbtlinf2 implements Structure.ByReference {
		
	};
	public static class ByValue extends odbtlinf2 implements Structure.ByValue {
		
	};
}
