package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbtlmng_mu_edge extends Structure {
	/** $ data no $ */
	public short data_no;
	/** $ edge no $ */
	public short edge_no;
	/** $ edge data $ */
	public odbtlmng_edge_data edge_data;
	public odbtlmng_mu_edge() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("data_no", "edge_no", "edge_data");
	}
	public odbtlmng_mu_edge(short data_no, short edge_no, odbtlmng_edge_data edge_data) {
		super();
		this.data_no = data_no;
		this.edge_no = edge_no;
		this.edge_data = edge_data;
	}
	public odbtlmng_mu_edge(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbtlmng_mu_edge implements Structure.ByReference {
		
	};
	public static class ByValue extends odbtlmng_mu_edge implements Structure.ByValue {
		
	};
}
