package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.Union;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbtlmng_edge_data extends Structure {
	public u_union u;
	public static class u_union extends Union {
		/** $ edge data $ */
		public iodbtlmng_mu_edge_data edge;
		/** $ tool life sum edge data $ */
		public iodbtllf tllf;
		/** $ tool life sum detile edge data $ */
		public iodbtllfd tllfd;
		public u_union() {
			super();
		}
		public u_union(iodbtlmng_mu_edge_data edge) {
			super();
			this.edge = edge;
			setType(iodbtlmng_mu_edge_data.class);
		}
		public u_union(iodbtllf tllf) {
			super();
			this.tllf = tllf;
			setType(iodbtllf.class);
		}
		public u_union(iodbtllfd tllfd) {
			super();
			this.tllfd = tllfd;
			setType(iodbtllfd.class);
		}
		public u_union(Pointer peer) {
			super(peer);
		}
		public static class ByReference extends u_union implements Structure.ByReference {
			
		};
		public static class ByValue extends u_union implements Structure.ByValue {
			
		};
	};
	public odbtlmng_edge_data() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("u");
	}
	public odbtlmng_edge_data(u_union u) {
		super();
		this.u = u;
	}
	public odbtlmng_edge_data(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbtlmng_edge_data implements Structure.ByReference {
		
	};
	public static class ByValue extends odbtlmng_edge_data implements Structure.ByValue {
		
	};
}
