package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbusbfile extends Structure {
	/** size */
	public NativeLong size;
	/** attribute */
	public short attribute;
	/** information */
	public short long_name;
	/** time stamp */
	public short year;
	/** time stamp */
	public byte mon;
	/** time stamp */
	public byte day;
	/** time stamp */
	public byte hour;
	/** time stamp */
	public byte min;
	/** time stamp */
	public byte sec;
	public byte dummy;
	/** file name */
	public byte[] fname = new byte[36];
	/** comment */
	public byte[] comment = new byte[64];
	public odbusbfile() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("size", "attribute", "long_name", "year", "mon", "day", "hour", "min", "sec", "dummy", "fname", "comment");
	}
	public odbusbfile(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbusbfile implements Structure.ByReference {
		
	};
	public static class ByValue extends odbusbfile implements Structure.ByValue {
		
	};
}
