package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class odbusegrp extends Structure {
	/** next use group number */
	public NativeLong next;
	/** using group number */
	public NativeLong use;
	/** selecting group number */
	public NativeLong slct;
	/** next use optional group number */
	public NativeLong opt_next;
	/** using optional group number */
	public NativeLong opt_use;
	/** selecting optional group number */
	public NativeLong opt_slct;
	public odbusegrp() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("next", "use", "slct", "opt_next", "opt_use", "opt_slct");
	}
	public odbusegrp(NativeLong next, NativeLong use, NativeLong slct, NativeLong opt_next, NativeLong opt_use, NativeLong opt_slct) {
		super();
		this.next = next;
		this.use = use;
		this.slct = slct;
		this.opt_next = opt_next;
		this.opt_use = opt_use;
		this.opt_slct = opt_slct;
	}
	public odbusegrp(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends odbusegrp implements Structure.ByReference {
		
	};
	public static class ByValue extends odbusegrp implements Structure.ByValue {
		
	};
}
