package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class out_statinfo_dmg extends Structure {
	/** \ufffd\ufffd\ufffdg\ufffdp */
	public short[] dummy = new short[1];
	/** DMG Netservice\ufffdX\ufffde??\ufffdX\ufffd\ufffd\ufffd */
	public short dmg;
	/** \ufffd\ufffd\ufffdg\ufffdp */
	public short[] dummy1 = new short[7];
	public out_statinfo_dmg() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("dummy", "dmg", "dummy1");
	}
	public out_statinfo_dmg(short dummy[], short dmg, short dummy1[]) {
		super();
		if ((dummy.length != this.dummy.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.dummy = dummy;
		this.dmg = dmg;
		if ((dummy1.length != this.dummy1.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.dummy1 = dummy1;
	}
	public out_statinfo_dmg(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends out_statinfo_dmg implements Structure.ByReference {
		
	};
	public static class ByValue extends out_statinfo_dmg implements Structure.ByValue {
		
	};
}
