package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.Union;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class OUT_PBMPRM extends Structure {
	public prm_union prm;
	public static class prm_union extends Union {
		public T_BUS_PARA bus_para;
		public T_MODE_ADDR_ALLOC mode_addr_alloc;
		public T_SLAVE_SUB_PARA slv_sub_para;
		public T_SLAVE_PARA slv_para;
		public T_DGN_ADDR_ALLOC dgn_addr_alloc;
		public T_MODULE_DATA module_data;
		public T_DIDO_ADDR_ALLOC dido_addr_alloc;
		public prm_union() {
			super();
		}
		public prm_union(T_BUS_PARA bus_para) {
			super();
			this.bus_para = bus_para;
			setType(T_BUS_PARA.class);
		}
		public prm_union(T_MODE_ADDR_ALLOC mode_addr_alloc) {
			super();
			this.mode_addr_alloc = mode_addr_alloc;
			setType(T_MODE_ADDR_ALLOC.class);
		}
		public prm_union(T_SLAVE_SUB_PARA slv_sub_para) {
			super();
			this.slv_sub_para = slv_sub_para;
			setType(T_SLAVE_SUB_PARA.class);
		}
		public prm_union(T_SLAVE_PARA slv_para) {
			super();
			this.slv_para = slv_para;
			setType(T_SLAVE_PARA.class);
		}
		public prm_union(T_DGN_ADDR_ALLOC dgn_addr_alloc) {
			super();
			this.dgn_addr_alloc = dgn_addr_alloc;
			setType(T_DGN_ADDR_ALLOC.class);
		}
		public prm_union(T_MODULE_DATA module_data) {
			super();
			this.module_data = module_data;
			setType(T_MODULE_DATA.class);
		}
		public prm_union(T_DIDO_ADDR_ALLOC dido_addr_alloc) {
			super();
			this.dido_addr_alloc = dido_addr_alloc;
			setType(T_DIDO_ADDR_ALLOC.class);
		}
		public prm_union(Pointer peer) {
			super(peer);
		}
		public static class ByReference extends prm_union implements Structure.ByReference {
			
		};
		public static class ByValue extends prm_union implements Structure.ByValue {
			
		};
	};
	public OUT_PBMPRM() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("prm");
	}
	public OUT_PBMPRM(prm_union prm) {
		super();
		this.prm = prm;
	}
	public OUT_PBMPRM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends OUT_PBMPRM implements Structure.ByReference {
		
	};
	public static class ByValue extends OUT_PBMPRM implements Structure.ByValue {
		
	};
}
