package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class OUT_PBSSTATUS2 extends Structure {
	public byte config_sts;
	public byte param_sts;
	public byte watchdog_sts;
	public byte pad1;
	public short ident_no;
	public byte sts;
	public byte pad2;
	public OUT_PBSSTATUS2() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("config_sts", "param_sts", "watchdog_sts", "pad1", "ident_no", "sts", "pad2");
	}
	public OUT_PBSSTATUS2(byte config_sts, byte param_sts, byte watchdog_sts, byte pad1, short ident_no, byte sts, byte pad2) {
		super();
		this.config_sts = config_sts;
		this.param_sts = param_sts;
		this.watchdog_sts = watchdog_sts;
		this.pad1 = pad1;
		this.ident_no = ident_no;
		this.sts = sts;
		this.pad2 = pad2;
	}
	public OUT_PBSSTATUS2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends OUT_PBSSTATUS2 implements Structure.ByReference {
		
	};
	public static class ByValue extends OUT_PBSSTATUS2 implements Structure.ByValue {
		
	};
}
