package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class OUT_USBLOG extends Structure {
	public short Count;
	public byte[] reserve = new byte[14];
	public OUT_USBLOG1SHOT[] logData = new OUT_USBLOG1SHOT[15];
	public OUT_USBLOG() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("Count", "reserve", "logData");
	}
	public OUT_USBLOG(short Count, byte reserve[], OUT_USBLOG1SHOT logData[]) {
		super();
		this.Count = Count;
		if ((reserve.length != this.reserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.reserve = reserve;
		if ((logData.length != this.logData.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.logData = logData;
	}
	public OUT_USBLOG(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends OUT_USBLOG implements Structure.ByReference {
		
	};
	public static class ByValue extends OUT_USBLOG implements Structure.ByValue {
		
	};
}
