package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class OUT_CHGMODERESULT extends Structure {
	public byte crnt_mode;
	public byte pad;
	public short result;
	public OUT_CHGMODERESULT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("crnt_mode", "pad", "result");
	}
	public OUT_CHGMODERESULT(byte crnt_mode, byte pad, short result) {
		super();
		this.crnt_mode = crnt_mode;
		this.pad = pad;
		this.result = result;
	}
	public OUT_CHGMODERESULT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends OUT_CHGMODERESULT implements Structure.ByReference {
		
	};
	public static class ByValue extends OUT_CHGMODERESULT implements Structure.ByValue {
		
	};
}
