package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class prgdir2 extends Structure {
	public short number;
	public NativeLong length;
	public byte[] comment = new byte[51];
	public byte dummy;
	public prgdir2() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("number", "length", "comment", "dummy");
	}
	public prgdir2(short number, NativeLong length, byte comment[], byte dummy) {
		super();
		this.number = number;
		this.length = length;
		if ((comment.length != this.comment.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.comment = comment;
		this.dummy = dummy;
	}
	public prgdir2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends prgdir2 implements Structure.ByReference {
		
	};
	public static class ByValue extends prgdir2 implements Structure.ByValue {
		
	};
}
