package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class realmes64 extends Structure {
	/** data of real measeure */
	public double mes_val;
	/** decimal point of real measeure */
	public NativeLong dec_val;
	/** dummy */
	public NativeLong dummy;
	public realmes64() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("mes_val", "dec_val", "dummy");
	}
	public realmes64(double mes_val, NativeLong dec_val, NativeLong dummy) {
		super();
		this.mes_val = mes_val;
		this.dec_val = dec_val;
		this.dummy = dummy;
	}
	public realmes64(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends realmes64 implements Structure.ByReference {
		
	};
	public static class ByValue extends realmes64 implements Structure.ByValue {
		
	};
}
