package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class realmes extends Structure {
	/** data of real measeure */
	public NativeLong mes_val;
	/** decimal point of real measeure */
	public NativeLong dec_val;
	public realmes() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("mes_val", "dec_val");
	}
	public realmes(NativeLong mes_val, NativeLong dec_val) {
		super();
		this.mes_val = mes_val;
		this.dec_val = dec_val;
	}
	public realmes(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends realmes implements Structure.ByReference {
		
	};
	public static class ByValue extends realmes implements Structure.ByValue {
		
	};
}
