package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class T_MAXMODLENPRM extends Structure {
	public byte slv_no;
	public byte slt_no;
	public byte max_mod_len;
	public byte pad;
	public T_MAXMODLENPRM() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("slv_no", "slt_no", "max_mod_len", "pad");
	}
	public T_MAXMODLENPRM(byte slv_no, byte slt_no, byte max_mod_len, byte pad) {
		super();
		this.slv_no = slv_no;
		this.slt_no = slt_no;
		this.max_mod_len = max_mod_len;
		this.pad = pad;
	}
	public T_MAXMODLENPRM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends T_MAXMODLENPRM implements Structure.ByReference {
		
	};
	public static class ByValue extends T_MAXMODLENPRM implements Structure.ByValue {
		
	};
}
