package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tag_ODBMSUYTERM extends Structure {
	public short data;
	public short dummy;
	public tag_ODBMSUYTERM() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("data", "dummy");
	}
	public tag_ODBMSUYTERM(short data, short dummy) {
		super();
		this.data = data;
		this.dummy = dummy;
	}
	public tag_ODBMSUYTERM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tag_ODBMSUYTERM implements Structure.ByReference {
		
	};
	public static class ByValue extends tag_ODBMSUYTERM implements Structure.ByValue {
		
	};
}
