package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagIODBPITCHBLK extends Structure {
	public short group_num;
	public tagIODBPITCHBLK.pginf_struct[] pginf = new tagIODBPITCHBLK.pginf_struct[8];
	public static class pginf_struct extends Structure {
		public NativeLong s_no;
		public NativeLong e_no;
		public short attr;
		public pginf_struct() {
			super();
		}
		protected List<? > getFieldOrder() {
			return Arrays.asList("s_no", "e_no", "attr");
		}
		public pginf_struct(NativeLong s_no, NativeLong e_no, short attr) {
			super();
			this.s_no = s_no;
			this.e_no = e_no;
			this.attr = attr;
		}
		public pginf_struct(Pointer peer) {
			super(peer);
		}
		public static class ByReference extends pginf_struct implements Structure.ByReference {
			
		};
		public static class ByValue extends pginf_struct implements Structure.ByValue {
			
		};
	};
	public tagIODBPITCHBLK() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("group_num", "pginf");
	}
	public tagIODBPITCHBLK(short group_num, tagIODBPITCHBLK.pginf_struct pginf[]) {
		super();
		this.group_num = group_num;
		if ((pginf.length != this.pginf.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pginf = pginf;
	}
	public tagIODBPITCHBLK(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagIODBPITCHBLK implements Structure.ByReference {
		
	};
	public static class ByValue extends tagIODBPITCHBLK implements Structure.ByValue {
		
	};
}
