package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagODBIFSBSPAMP extends Structure {
	/** Slave Number */
	public short slave_num;
	/** Amp Name */
	public byte[] name = new byte[8];
	/** Amp Series */
	public byte[] series = new byte[12];
	/** Amp Power */
	public byte[] pwr = new byte[8];
	/** Spindle number for Auto Set */
	public short as_spdl_num;
	/** Spindle name for Auto Set */
	public byte[] as_spdl_name = new byte[4];
	public tagODBIFSBSPAMP() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("slave_num", "name", "series", "pwr", "as_spdl_num", "as_spdl_name");
	}
	public tagODBIFSBSPAMP(short slave_num, byte name[], byte series[], byte pwr[], short as_spdl_num, byte as_spdl_name[]) {
		super();
		this.slave_num = slave_num;
		if ((name.length != this.name.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.name = name;
		if ((series.length != this.series.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.series = series;
		if ((pwr.length != this.pwr.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pwr = pwr;
		this.as_spdl_num = as_spdl_num;
		if ((as_spdl_name.length != this.as_spdl_name.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.as_spdl_name = as_spdl_name;
	}
	public tagODBIFSBSPAMP(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagODBIFSBSPAMP implements Structure.ByReference {
		
	};
	public static class ByValue extends tagODBIFSBSPAMP implements Structure.ByValue {
		
	};
}
