package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagODBIFSBSVAMP extends Structure {
	/** Slave Number */
	public short slave_num;
	/** Amp Name */
	public byte[] name = new byte[8];
	/** Amp Series */
	public byte[] series = new byte[12];
	/** Amp Current */
	public byte[] cur = new byte[8];
	/** Axis number for Auto Set */
	public short as_axis_num;
	/** Axis name for Auto Set */
	public byte[] as_axis_name = new byte[4];
	public tagODBIFSBSVAMP() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("slave_num", "name", "series", "cur", "as_axis_num", "as_axis_name");
	}
	public tagODBIFSBSVAMP(short slave_num, byte name[], byte series[], byte cur[], short as_axis_num, byte as_axis_name[]) {
		super();
		this.slave_num = slave_num;
		if ((name.length != this.name.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.name = name;
		if ((series.length != this.series.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.series = series;
		if ((cur.length != this.cur.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.cur = cur;
		this.as_axis_num = as_axis_num;
		if ((as_axis_name.length != this.as_axis_name.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.as_axis_name = as_axis_name;
	}
	public tagODBIFSBSVAMP(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagODBIFSBSVAMP implements Structure.ByReference {
		
	};
	public static class ByValue extends tagODBIFSBSVAMP implements Structure.ByValue {
		
	};
}
