package fwlib32;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagODBVOLCOMP extends Structure {
	public NativeLong[] comp = new NativeLong[5];
	public tagODBVOLCOMP() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("comp");
	}
	public tagODBVOLCOMP(NativeLong comp[]) {
		super();
		if ((comp.length != this.comp.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.comp = comp;
	}
	public tagODBVOLCOMP(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagODBVOLCOMP implements Structure.ByReference {
		
	};
	public static class ByValue extends tagODBVOLCOMP implements Structure.ByValue {
		
	};
}
