package fwlib32;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TSK_STS extends Structure {
	public short StsId;
	public byte[] Status = new byte[30];
	public TSK_STS() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("StsId", "Status");
	}
	public TSK_STS(short StsId, byte Status[]) {
		super();
		this.StsId = StsId;
		if ((Status.length != this.Status.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.Status = Status;
	}
	public TSK_STS(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TSK_STS implements Structure.ByReference {
		
	};
	public static class ByValue extends TSK_STS implements Structure.ByValue {
		
	};
}
